[telegram]
token = "YOUR API TOKEN"
admin_chat_id = 0 #  type /myid in your bot to get you chat id
lang="rus" # rus/eng

[server]
ip = "0.0.0.0"
port = "3000"
ping_interval = 5 # seconds
data_secure_key = "LfX^7B)0t)u_%X-pW7rrZbptQiRy^C35" # 32 SYMBOLS!!!